Update config.yml

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -128,9 +128,9 @@ jobs:
       - run:
           name: Smoke Test
           command: HTTPCODE=`curl -s -o /dev/null -w "%{http_code}" https://$HEROKU_APP_NAME.herokuapp.com/`
-                   if [ "$HTTPCODE" -ne 200 ]; then
-                     echo "heroku app not responding, failing deploy"
-                     exit 1
+                   if [[ "$HTTPCODE" -ne 200 ]]; then
+                     echo "heroku app not responding, failing deploy"\
+                     exit 1\
                    fi
 
 workflows:
