Update config.yml

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -57,7 +57,7 @@ jobs:
           command: sudo npm install netlify-cli -g
       - run:
           name: Deploy app
-          command: netlify deploy --prod --dir /tmp/server-doc --auth $ACCESS_TOKEN --site $NETLIFY_SITE_ID
+          command: netlify deploy --prod --dir=/tmp/server-doc --auth $ACCESS_TOKEN --site $NETLIFY_SITE_ID
   back-test-unit:
     docker:
       - image: circleci/node:dubnium-browsers
@@ -127,11 +127,12 @@ jobs:
           command: git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git main
       - run:
           name: Smoke Test
-          command: HTTPCODE=`curl -s -o /dev/null -w "%{http_code}" https://$HEROKU_APP_NAME.herokuapp.com/`
-                   if [[ "$HTTPCODE" -ne 200 ]]; then
-                     echo "heroku app not responding, failing deploy"\
-                     exit 1\
-                   fi
+          command : | 
+            HTTPCODE=`curl -s -o /dev/null -w "%{http_code}" https://$HEROKU_APP_NAME.herokuapp.com/`
+            if [ "$HTTPCODE" -ne 200 ];then
+              echo "heroku app not responding, failing deploy"
+              exit 1
+            fi
 
 workflows:
   version: 2
